(function(g){var window=this;var $Aa=function(a,b){return g.Ub(a,b)},M6=function(a){g.Dm(a,"zx",g.yb());
return a},N6=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.Gm(a.g,b,c)},aBa=function(a,b){var c=[];
g.pk(b,function(a){try{var b=g.dD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.cD(b)&&c.push(a):c.push(a)},a);
return c},bBa=function(a,b){var c=aBa(a,b);
(0,g.B)(c,function(a){g.dD.prototype.remove.call(this,a)},a)},cBa=function(a){if(a.Ad){if(a.Ad.locationOverrideToken)return{locationOverrideToken:a.Ad.locationOverrideToken};
if(null!=a.Ad.latitudeE7&&null!=a.Ad.longitudeE7)return{latitudeE7:a.Ad.latitudeE7,longitudeE7:a.Ad.longitudeE7}}return null},dBa=function(a,b,c,d){var e=new g.um(null,void 0);
a&&g.vm(e,a);b&&g.wm(e,b);c&&g.xm(e,c);d&&g.ym(e,d);return e},eBa=function(a){g.TF[a]&&(a=g.TF[a],(0,g.B)(a,function(a){g.RF[a]&&delete g.RF[a]}),a.length=0)},fBa=function(a){var b=g.QF();
if(b)if(b.clear(a),a)eBa(a);else for(var c in g.TF)eBa(c)},O6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.om;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gBa(this,a.capabilities||""),hBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},gBa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Ga($Aa,iBa)).forEach(function(b){a.capabilities.add(b)})},hBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},P6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kBa=function(a){return new P6(a)},lBa=function(a){return g.Aa(a)?(0,g.G)(a,kBa):[]},R6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},S6=function(a){return g.Aa(a)?"["+(0,g.G)(a,R6).join(",")+"]":"null"},T6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},U6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},V6=function(a,b){return g.La(a,function(a){return Q6(a,b)})},nBa=function(){var a=(0,g.NG)();
a&&bBa(a,a.g.Vd(!0))},W6=function(){var a=g.QG("yt-remote-connected-devices")||[];
g.gb(a);return a},oBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},pBa=function(a){g.PG("yt-remote-connected-devices",a,86400)},Y6=function(){if(X6)return X6;
var a=g.QG("yt-remote-device-id");a||(a=T6(),g.PG("yt-remote-device-id",a,31536E3));for(var b=W6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return X6=d},Z6=function(){var a=W6(),b=Y6();
g.Pa(a,b);g.SG()&&g.jb(a,b);a=oBa(a);if(g.Qa(a))try{g.zG("remote_sid")}catch(c){}else try{g.yG("remote_sid",a.join(","),-1)}catch(c){}},qBa=function(){return g.QG("yt-remote-session-browser-channel")},rBa=function(){return g.QG("yt-remote-local-screens")||[]},sBa=function(){g.PG("yt-remote-lounge-token-expiration",!0,86400)},tBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(rBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.cm)(c,function(a){return!g.Pa(b,a)})&&sBa();
g.PG("yt-remote-local-screens",a,31536E3)},uBa=function(a,b){g.PG("yt-remote-session-browser-channel",a);
g.PG("yt-remote-session-screen-id",b);var c=W6(),d=Y6();g.Pa(c,d)||c.push(d);pBa(c);Z6()},$6=function(a){a||(g.RG("yt-remote-session-screen-id"),g.RG("yt-remote-session-video-id"));
Z6();a=W6();g.Ua(a,Y6());pBa(a)},vBa=function(){if(!a7){var a=g.oD();
a&&(a7=new g.YC(a))}return a7?!!a7.get("yt-remote-use-staging-server"):!1},wBa=function(){var a=window.document.createElement("a");
g.$c(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},xBa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},yBa=function(){var a=wBa(),b=window.document.getElementById(a),c=b&&g.bF(b,"loaded");
c||b&&!c||(b=xBa(a,function(){g.bF(b,"loaded")||(g.aF(b,"loaded","true"),g.XF(a),g.XD(g.Ga(fBa,a),0))}))},b7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},zBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},c7=function(a){a.length?ABa(a.shift(),function(){c7(a)}):d7()},BBa=function(a){return"chrome-extension://"+a+e7},ABa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},f7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},d7=function(){var a=zBa();
a&&a(!1,"No cast extension found")},g7=function(){if(CBa){var a=2,b=zBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ABa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",d7,c)}},DBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(g7(),a({command:"cast.sender.init"}))},EBa=function(){g7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);c7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+e7,"//www.gstatic.com/eureka/clank"+e7])},h7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.rd=b;this.B=(0,g.z)(this.PJ,this);this.g=!1;this.l=0;this.o=this.Ca=null;this.A=[]},i7=function(){},j7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Km(this);this.l=new g.rg;this.l.setInterval(250)},GBa=function(a,b,c){a.Mj=1;
a.nh=M6(b.clone());a.Ti=c;a.B=!0;FBa(a,null)},k7=function(a,b,c,d,e){a.Mj=1;
a.nh=M6(b.clone());a.Ti=null;a.B=c;e&&(a.iE=!1);FBa(a,d)},FBa=function(a,b){a.Ck=(0,g.F)();
l7(a);a.Kh=a.nh.clone();N6(a.Kh,"t",a.C);a.Um=0;a.Rc=a.g.Sr(a.g.Km()?b:null);0<a.Hs&&(a.Qp=new g.Tk((0,g.z)(a.zF,a,a.Rc),a.Hs));a.W.U(a.Rc,"readystatechange",a.nV);var c=a.oi?g.bc(a.oi):{};a.Ti?(a.Eq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Kh,a.Eq,a.Ti,c)):(a.Eq="GET",a.iE&&!g.zd&&(c.Connection="close"),a.Rc.send(a.Kh,a.Eq,null,c));a.g.Af(1)},JBa=function(a,b,c){for(var d=!0;!a.Yh&&a.Um<c.length;){var e=HBa(a,c);
if(e==m7){4==b&&(a.oh=4,n7(15),d=!1);break}else if(e==IBa){a.oh=4;n7(16);d=!1;break}else o7(a,e)}4==b&&0==c.length&&(a.oh=1,n7(17),d=!1);a.Gf=a.Gf&&d;d||(p7(a),q7(a))},HBa=function(a,b){var c=a.Um,d=b.indexOf("\n",c);
if(-1==d)return m7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return IBa;d+=1;if(d+c>b.length)return m7;var e=b.substr(d,c);a.Um=d+c;return e},LBa=function(a,b){a.Ck=(0,g.F)();
l7(a);var c=b?window.location.hostname:"";a.Kh=a.nh.clone();g.Dm(a.Kh,"DOMAIN",c);g.Dm(a.Kh,"t",a.C);try{a.Hf=new window.ActiveXObject("htmlfile")}catch(n){p7(a);a.oh=7;n7(22);q7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in r7)k=r7[l];else if(l in KBa)k=r7[l]=KBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=r7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.xc("b/12014412"),d);a.Hf.open();a.Hf.write(g.Uc(c));a.Hf.close();a.Hf.parentWindow.m=(0,g.z)(a.wU,a);a.Hf.parentWindow.d=(0,g.z)(a.sD,a,!0);a.Hf.parentWindow.rpcClose=(0,g.z)(a.sD,a,!1);c=a.Hf.createElement("DIV");a.Hf.parentWindow.document.body.appendChild(c);d=g.Lc(a.Kh.toString());d=g.qb(g.Ic(d));d=g.bd(g.xc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Uc(d);
a.g.Af(1)},l7=function(a){a.kw=(0,g.F)()+a.A;
MBa(a,a.A)},MBa=function(a,b){if(null!=a.Sk)throw Error("WatchDog timer not null");
a.Sk=s7((0,g.z)(a.MU,a),b)},t7=function(a){a.Sk&&(g.w.clearTimeout(a.Sk),a.Sk=null)},q7=function(a){a.g.Dz()||a.Yh||a.g.Cp(a)},p7=function(a){t7(a);
g.Ze(a.Qp);a.Qp=null;a.l.stop();g.Qm(a.W);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.Hf&&(a.Hf=null)},o7=function(a,b){try{a.g.lD(a,b),a.g.Af(4)}catch(c){}},OBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;NBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){OBa(a,b,c,d,f)},f)})}},NBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{u7(d),c(!0)}catch(e){}};
d.onerror=function(){try{u7(d),c(!1)}catch(e){}};
d.onabort=function(){try{u7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{u7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},u7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},PBa=function(a){this.g=a;
this.l=new i7},QBa=function(a){var b=v7(a.g,a.dl,"/mail/images/cleardot.gif");
M6(b);OBa(b.toString(),5E3,(0,g.z)(a.cJ,a),3,2E3);a.Af(1)},x7=function(a){var b=a.g.H;
if(null!=b)n7(5),b?(n7(11),w7(a.g,a,!1)):(n7(12),w7(a.g,a,!0));else if(a.ye=new j7(a,void 0,void 0,void 0),a.ye.oi=a.Fs,b=a.g,b=v7(b,b.Km()?a.Hl:null,a.Gs),n7(5),!g.xd||g.rc(10))N6(b,"TYPE","xmlhttp"),k7(a.ye,b,!1,a.Hl,!1);else{N6(b,"TYPE","html");var c=a.ye;a=!!a.Hl;c.Mj=3;c.nh=M6(b.clone());LBa(c,a)}},y7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new i7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},RBa=function(a,b){this.g=a;
this.map=b;this.context=null},SBa=function(a){g.af.call(this,"statevent",a)},TBa=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},UBa=function(a){g.af.call(this,"serverreachability",a)},XBa=function(a){VBa(a);
if(3==a.g){var b=a.sm++,c=a.mo.clone();g.Dm(c,"SID",a.o);g.Dm(c,"RID",b);g.Dm(c,"TYPE","terminate");z7(a,c);b=new j7(a,a.o,b,void 0);b.Mj=2;b.nh=M6(c.clone());(new window.Image).src=b.nh;b.Ck=(0,g.F)();l7(b)}WBa(a)},YBa=function(a){a.xJ(1,0);
a.mo=v7(a,null,a.Es);A7(a)},VBa=function(a){a.bh&&(a.bh.abort(),a.bh=null);
a.uc&&(a.uc.cancel(),a.uc=null);a.tg&&(g.w.clearTimeout(a.tg),a.tg=null);B7(a);a.be&&(a.be.cancel(),a.be=null);a.fh&&(g.w.clearTimeout(a.fh),a.fh=null)},ZBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new RBa(a.gQ++,b));2!=a.g&&3!=a.g||A7(a)},A7=function(a){a.be||a.fh||(a.fh=s7((0,g.z)(a.qD,a),0),a.Bj=0)},aCa=function(a,b){if(1==a.g){if(!b){a.sm=Math.floor(1E5*Math.random());
var c=a.sm++,d=new j7(a,"",c,void 0);d.oi=null;var e=C7(a),f=a.mo.clone();g.Dm(f,"RID",c);g.Dm(f,"CVER","1");z7(a,f);GBa(d,f,e);a.be=d;a.g=2}}else 3==a.g&&(b?$Ba(a,b):0==a.l.length||a.be||$Ba(a))},$Ba=function(a,b){if(b)if(6<a.bi){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.sm-1;var d=C7(a)}else c=b.D,d=b.Ti;else c=a.sm++,d=C7(a);var e=a.mo.clone();g.Dm(e,"SID",a.o);g.Dm(e,"RID",c);g.Dm(e,"AID",a.ak);z7(a,e);c=new j7(a,a.o,c,a.Bj+1);c.oi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.be=c;GBa(c,e,d)},z7=function(a,b){if(a.qd){var c=a.qd.iz();
c&&g.Kb(c,function(a,c){g.Dm(b,c,a)})}},C7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.bi&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.bi?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},bCa=function(a){a.uc||a.tg||(a.D=1,a.tg=s7((0,g.z)(a.pD,a),0),a.oj=0)},D7=function(a){if(a.uc||a.tg||3<=a.oj)return!1;
a.D++;a.tg=s7((0,g.z)(a.pD,a),cCa(a,a.oj));a.oj++;return!0},w7=function(a,b,c){a.Dq=c;
a.Wf=b.Eg;a.C||YBa(a)},B7=function(a){null!=a.di&&(g.w.clearTimeout(a.di),a.di=null)},cCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},E7=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.fW,a);c||(c=new g.um("//www.google.com/images/cleardot.gif"),M6(c));NBa(c.toString(),1E4,d)}else n7(2);dCa(a,b)},dCa=function(a,b){a.g=0;
a.qd&&a.qd.Zx(b);WBa(a);VBa(a)},WBa=function(a){a.g=0;
a.Wf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.Gr();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.qd.Gr(b)}},v7=function(a,b,c){var d=g.Em(c);
if(""!=d.l)b&&g.wm(d,b+"."+d.l),g.xm(d,d.B);else{var e=window.location;d=dBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.tl&&g.Kb(a.tl,function(a,b){g.Dm(d,b,a)});
g.Dm(d,"VER",a.bi);z7(a,d);return d},s7=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},n7=function(a){F7.dispatchEvent(new SBa(F7,a))},eCa=function(){},fCa=function(a,b){this.action=a;
this.params=b||{}},G7=function(a,b){g.M.call(this);
this.g=new g.Yt(this.nU,0,this);g.N(this,this.g);this.rd=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},H7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.XC;this.l=new G7(this.PW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},gCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Dq,sessionId:a.g.o,arrayId:a.g.ak}},hCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&aCa(a.g),XBa(a.g));a.F=0},I7=function(a){return!!a.g&&3==a.g.g},iCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},J7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.l=!1))},K7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},L7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ga(a.A,d,!0),onError:g.Ga(a.o,e),xd:g.Ga(a.B,e)};c&&(a.Ob=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.nE(b,a)},mCa=function(){var a=jCa;
kCa();M7.push(a);lCa(M7)},N7=function(a,b){kCa();
var c=M7,d=nCa(a,String(b));g.Qa(c)?oCa(d):(lCa(c),(0,g.B)(c,function(a){a(d)}))},kCa=function(){M7||(M7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",M7,void 0))},oCa=function(a){var b=(O7+1)%50;
O7=b;P7[b]=a;Q7||(Q7=49==b)},lCa=function(a){var b=P7;
if(b[0]){var c=O7,d=Q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
P7=Array(50);O7=-1;Q7=!1}},nCa=function(a,b){var c=((0,g.F)()-pCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},R7=function(a){g.IF.call(this);
this.D=a;this.g=[]},qCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!U6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qCa(a,b[d])||c;return c},sCa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},S7=function(a,b,c,d){g.IF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ca=window.NaN},U7=function(a){R7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;T7(this);this.info("Initializing with "+S6(this.g))},tCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=K7(a.o,"/pairing/get_lounge_token_batch");
L7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.cK,a),(0,g.z)(a.bK,a))}},T7=function(a){var b=lBa(rBa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return rCa(a,b)},V7=function(a,b){tBa((0,g.G)(a.g,jBa));
b&&sBa()},X7=function(a,b){g.IF.call(this);
this.C=b;var c=g.QG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;W7("Initialized with "+g.yg(this.g))},uCa=function(a,b,c){var d=K7(a.B,"/pairing/get_screen_availability");
L7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},Y7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(W7("Updated online screens: "+g.yg(a.g)),a.g=b,a.R("screenChange"));vCa(a)},Z7=function(a){(0,window.isNaN)(a.o)||g.ZD(a.o);
a.o=g.XD((0,g.z)(a.Av,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},W7=function(a){N7("OnlineScreenService",a)},wCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},vCa=function(a){a=g.Rb(g.Lb(a.g,function(a){return a}));
g.gb(a);a.length?g.PG("yt-remote-online-screen-ids",a.join(","),60):g.RG("yt-remote-online-screen-ids")},$7=function(a){R7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};xCa(this)},zCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.qe();if(k=(c?V6(k,c):null)||V6(k,b)){k.uuid=b;var l=a8(a,k);uCa(a.l,l,function(a){e(a?l:null)})}else c?yCa(a,c,(0,g.z)(function(a){var f=a8(this,new P6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},ACa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},yCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Ob:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.nE(K7(a.C,"/pairing/get_lounge_token_batch"),e)},BCa=function(a){a.g=a.o.qe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+S6(a.g))},xCa=function(a){b8(a);
a.o=new U7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.rK,a));BCa(a);a.A=lBa(g.QG("yt-remote-automatic-screen-cache")||[]);b8(a);a.info("Initializing automatic screens: "+S6(a.A));a.l=new X7(a.C,(0,g.z)(a.qe,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},a8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=V6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.PG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,jBa)));b8(a);a.B[b.uuid]=b.id;g.PG("yt-remote-device-id-map",a.B,31536E3);return b},b8=function(a){a.B=g.QG("yt-remote-device-id-map")||{}},c8=function(a,b,c){g.IF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},d8=function(a,b){N7(a.K,b)},e8=function(a,b){c8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.VW,this);this.B=(0,g.z)(this.YU,this);this.A=g.XD((0,g.z)(function(){CCa(this,null)},this),12E4)},DCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){d8(this,"Failed to send message: getMdxSessionStatus.")},a)):d8(a,"Sending yt message without session: "+g.yg(b))},CCa=function(a,b){g.ZD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Dp,a),d=(0,g.z)(a.we,a);a.uz(b,c,d,5)}}else a.we(Error("Waiting for session status timed out."))},f8=function(a,b,c){c8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.YW,this);this.g=g.y},ECa=function(a){a.g=a.H.GF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Dp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.we(a)},a))},FCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}vBa()&&(b.env_useStageMdx=1);return g.Og(b)},g8=function(a,b){c8.call(this,a,b,"ManualSession");
this.g=g.XD((0,g.z)(this.ck,this,null),150)},h8=function(a,b,c,d){g.IF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.wT,this)},GCa=function(a,b){return b?g.La(a.o,function(a){return Q6(b,a.label)},a):null},i8=function(a){N7("Controller",a)},jCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},j8=function(a){return a.B||!!a.o.length||!!a.g},k8=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.nD,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.ck(null)):a.R("yt-remote-cast2-session-change",null))},HCa=function(a){var b=a.l.FF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&Q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NCa=function(a,b,c,d,e,f,k){ICa()?JCa(b,e,f,k)&&(m8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?KCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KCa(a,c):(n8("Failed to load cast API: "+d),o8(!1),m8(!1),g.RG("yt-remote-cast-available"),g.RG("yt-remote-cast-receiver"),LCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):yBa():f7("CriOS")?DBa():f7("Android")&&f7("Chrome/")&&window.navigator.presentation?EBa():window.chrome&&window.navigator.presentation&&!f7("Edge")?(g7(),c7(MCa.map(BBa))):d7())):l8("Cannot initialize because not running Chrome")},LCa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);OCa(!1);g.VF(q8);q8.length=0},r8=function(){return!!g.QG("yt-remote-cast-installed")},PCa=function(){var a=g.QG("yt-remote-cast-receiver");
return a?a.friendlyName:null},QCa=function(){l8("clearCurrentReceiver");
g.RG("yt-remote-cast-receiver")},RCa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.UF("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},ICa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.CI||a},SCa=function(a,b){p8().init(a,b)},JCa=function(a,b,c,d){var e=!1;
p8()||(a=new h8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.PG("yt-remote-cast-available",a);g.YF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){l8("onReceiverSelected: "+a.friendlyName);
g.PG("yt-remote-cast-receiver",a);g.YF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){l8("onReceiverResumed: "+a.friendlyName);
g.PG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){l8("onSessionChange: "+R6(a));
a||g.RG("yt-remote-cast-receiver");g.YF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
l8("cloudview.createSingleton_: "+e);return e},p8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},KCa=function(a,b){o8(!0);
m8(!1);SCa(a,function(a){a?(OCa(!0),g.XF("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.RG("yt-remote-cast-available"),g.RG("yt-remote-cast-receiver"),LCa());b(a)})},l8=function(a){N7("cloudview",a)},n8=function(a){N7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.PG("yt-remote-cast-installed",a)},s8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},OCa=function(a){l8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Zf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Zf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},x8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},y8=function(a,b){a.F=b;
a.D=(0,g.F)()},z8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},D8=function(a,b){g.IF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.nC;this.o=this.l=null;this.H=(0,g.z)(this.QQ,this);this.D=(0,g.z)(this.xm,this);this.F=(0,g.z)(this.PQ,this);this.I=(0,g.z)(this.dR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tw,this),TCa(this))):c=3;0!=c&&(b?this.tw(c):g.XD((0,g.z)(function(){this.tw(c)},this),0));
var d=RCa();d&&C8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},E8=function(a){return new v8(a.A.getPlayerContextData())},TCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ga(this.rT,a),this))},a)},UCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},F8=function(a,b){50>a.B.Dc()&&g.pC(a.B,b)},H8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.g&&(d.g=b);G8(a,d)},I8=function(a,b,c){a.A.sendMessage(b,c)},G8=function(a,b){UCa(a);
a.A.setPlayerContextData(B8(b));TCa(a)},C8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.xm(null));
a.o=b;a.o&&(N7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.xm(a.o.media[0]))},VCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&N7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;y8(d,a.l.getEstimatedTime());G8(a,d)}else N7("CP","No cast media video. Ignoring state update.")},J8=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),I8(this,b,c))},a)},K8=function(a,b,c){g.IF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.T=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.T.push(g.rF(window,"beforeunload",(0,g.z)(this.TJ,this)));this.l=[];this.Za=new v8;this.Z=b.id;this.g=WCa(this,c);this.g.subscribe("handlerOpened",this.VQ,this);this.g.subscribe("handlerClosed",this.RQ,this);this.g.subscribe("handlerError",this.TQ,this);this.g.subscribe("handlerMessage",this.UQ,this);iCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.SG()&&g.PG("yt-remote-session-video-id",a)},this)},L8=function(a){N7("conn",a)},WCa=function(a,b){return new H7(K7(a.ra,"/bc"),b)},M8=function(a,b){a.R("proxyStateChange",b)},XCa=function(a){a.B=g.XD((0,g.z)(function(){L8("Connecting timeout");
this.C(1)},a),2E4)},N8=function(a){g.ZD(a.B);
a.B=window.NaN},O8=function(a){g.ZD(a.K);
a.K=window.NaN},YCa=function(a){P8(a);
a.J=g.XD((0,g.z)(function(){Q8(this,"getNowPlaying")},a),2E4)},P8=function(a){g.ZD(a.J);
a.J=window.NaN},$Ca=function(a,b){b&&(N8(a),O8(a));
b==(I7(a.g)&&(0,window.isNaN)(a.B))?b&&(M8(a,1),Q8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),M8(a,1),Q8(a,"getNowPlaying"),ZCa(a)):a.C(1)},aDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Xb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},bDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;A8(a.Za,c,d);a.R("remoteQueueChange")},dDa=function(a,b){b.params=b.params||{};
bDa(a,b);cDa(a,b);a.R("autoplayDismissed")},cDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
y8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?YCa(a):P8(a);
a.R("remotePlayerChange")},eDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);y8(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},fDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},gDa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},hDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Zf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},ZCa=function(a){g.ZD(a.I);
a.I=g.XD((0,g.z)(a.C,a,1),864E5)},Q8=function(a,b,c){c?L8("Sending: action="+b+", params="+g.yg(c)):L8("Sending: action="+b);
a.g.sendMessage(b,c)},R8=function(a){R7.call(this,"ScreenServiceProxy");
this.fd=a;this.l=[];this.l.push(this.fd.$_s("screenChange",(0,g.z)(this.TW,this)));this.l.push(this.fd.$_s("onlineScreenChange",(0,g.z)(this.SS,this)))},mDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.RD("MDX_CONFIG")||b;nBa();Z6();S8||(S8=new J7(b?b.loungeApiHost:void 0),vBa()&&(S8.g="/api/loungedev"));T8||(T8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",T8,void 0));iDa();var c=U8();if(!c){var d=new $7(S8);g.va("yt.mdx.remote.screenService_",d,void 0);c=U8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);NCa(a,d,function(a){a?V8()&&u8(V8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.YF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),W8("Initializing: "+g.yg(b)),X8.push(g.UF("yt-remote-cast2-availability-change",function(){g.YF("yt-remote-receiver-availability-change")})),X8.push(g.UF("yt-remote-cast2-receiver-selected",function(){Y8(null);
g.YF("yt-remote-auto-connect","cast-selector-receiver")})),X8.push(g.UF("yt-remote-cast2-receiver-resumed",function(){g.YF("yt-remote-receiver-resumed","cast-selector-receiver")})),X8.push(g.UF("yt-remote-cast2-session-change",jDa)),X8.push(g.UF("yt-remote-connection-change",function(a){a?u8(V8(),"YouTube TV"):Z8()||(u8(null,null),QCa())})),a=$8(),b.isAuto&&(a.id+="#dial"),g.OF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),W8(" -- with channel params: "+
g.yg(a)),kDa(a),c.start(),V8()||lDa())},oDa=function(){var a=nDa();
r8()&&g.QG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nDa=function(){var a=U8().fd.$_gos();
var b=a9();b&&b9()&&(U6(a,b)||a.push(b));return mBa(a)},c9=function(){var a=pDa();
!a&&r8()&&PCa()&&(a={key:"cast-selector-receiver",name:PCa()});return a},pDa=function(){var a=nDa(),b=a9();
b||(b=Z8());return g.La(a,function(a){return b&&Q6(b,a.key)?!0:!1})},a9=function(){var a=V8();
if(!a)return null;var b=U8().qe();return V6(b,a)},jDa=function(a){W8("remote.onCastSessionChange_: "+R6(a));
if(a){var b=a9();b&&b.id==a.id?u8(b.id,"YouTube TV"):(b&&d9(),e9(a,1))}else b9()&&d9()},d9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=b9();a&&(a.disconnect(1),f9(null))},g9=function(){var a=b9();
return!!a&&3!=a.getProxyState()},W8=function(a){N7("remote",a)},U8=function(){if(!h9){var a=g.x("yt.mdx.remote.screenService_");
h9=a?new R8(a):null}return h9},V8=function(){return g.x("yt.mdx.remote.currentScreenId_")},qDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},rDa=function(){return g.x("yt.mdx.remote.connectData_")},Y8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},b9=function(){return g.x("yt.mdx.remote.connection_")},f9=function(a){var b=b9();
Y8(null);a||qDa("");g.va("yt.mdx.remote.connection_",a,void 0);T8&&((0,g.B)(T8,function(b){b(a)}),T8.length=0);
b&&!a?g.YF("yt-remote-connection-change",!1):!b&&a&&g.YF("yt-remote-connection-change",!0)},Z8=function(){var a=g.SG();
if(!a)return null;var b=U8().qe();return V6(b,a)},e9=function(a,b){a9()&&a9();
qDa(a.id);var c=new K8(S8,a,$8());c.connect(b,rDa());c.subscribe("beforeDisconnect",function(a){g.YF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){b9()&&f9(null)});
f9(c)},lDa=function(){var a=Z8();
a?(W8("Resume connection to: "+R6(a)),e9(a,0)):($6(),QCa(),W8("Skipping connecting because no session screen found."))},iDa=function(){var a=$8();
if(g.Xb(a)){a=Y6();var b=g.QG("yt-remote-session-name")||"",c=g.QG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},$8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},kDa=function(a){a?(g.PG("yt-remote-session-app",a.app),g.PG("yt-remote-session-name",a.name)):(g.RG("yt-remote-session-app"),g.RG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.FF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.kS);this.o.O(b,"captionschanged",this.OQ);this.o.O(b,"captionssettingschanged",this.TE);this.o.O(b,"videoplayerreset",this.Ep);this.o.O(b,"mdxautoplaycancel",this.bJ);this.T=this.o.O(b,"onVolumeChange",this.XC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.kD,this);c.subscribe("remotePlayerChange",this.Am,this);c.subscribe("remoteQueueChange",this.Ep,this);c.subscribe("autoplayUpNext",this.IC,
this);c.subscribe("previousNextChange",this.hD,this);c.subscribe("nowAutoplaying",this.ZC,this);c.subscribe("autoplayDismissed",this.HC,this);this.suggestion=null;this.H=new g.qP(64);this.A=new g.Yt(this.PE,500,this);g.N(this,this.A);this.B=new g.Yt(this.QE,1E3,this);g.N(this,this.B);this.J=new h7(this.uW,0,this);g.N(this,this.J);this.C={};this.K=new g.Yt(this.pF,1E3,this);g.N(this,this.K);this.I=new g.Tk(this.NO,1E3,this);g.N(this,this.I);this.M=g.y;this.TE();this.Ep();this.Am()},j9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},sDa=function(a){j9(a,0);
a.A.stop();k9(a,new g.qP(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Li()},g.ec(c,b));a.g.DE(a.l.getVideoData(1).videoId,c);a.C=E8(a.g).l}},n9=function(a,b){var c=a.l.fg();
if(c){var d=c.oe();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Vj;f=cBa(f);var n=E8(c);l=l||0;var p={videoId:k,currentIndex:l};A8(n,k,l);g.t(b)&&(y8(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.yg(f));I8(c,"setPlaylist",p);e||G8(c,n);k9(a,new g.qP(1))},tDa=function(a,b){if(b){var c=a.l.yc("captions","tracklist",{oA:1});
c&&c.length?(a.l.Pd("captions","track",b),a.D=!1):(a.l.kk("captions"),a.D=!0)}else a.l.Pd("captions","track",{})},l9=function(a){return E8(a.g).videoId==a.l.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.H;if(!g.vP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.WU(a.l,d);a.H=b;uDa(a.F,c,b)}},o9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.Xoa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.l=new g.LV(this,250);g.N(this,this.l);this.A=a;this.O(a,"presentingplayerstatechange",this.B);vDa(this,g.TU(a))},vDa=function(a,b){if(3==a.A.Qa()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name};
c=g.X(b,128)?g.O0("\u062d\u062f\u062b \u062e\u0637\u0623 \u0641\u064a $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.O0("\u064a\u062a\u0645 \u0627\u0644\u062a\u0634\u063a\u064a\u0644 \u0639\u0644\u0649 $RECEIVER_NAME",c):g.O0("\u062a\u0645 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0640 $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},p9=function(a,b){g.VZ.call(this,"\u062a\u0634\u063a\u064a\u0644 \u0639\u0644\u0649",0,a,b);
this.l=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},q9=function(a){g.rV.call(this,a);
this.o={key:T6(),name:"\u0647\u0630\u0627 \u0627\u0644\u0643\u0645\u0628\u064a\u0648\u062a\u0631"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.qP(64);this.H=0;if(!g.UM(g.Y(this.g))){a=this.g;var b=g.HH(a);b&&(b=b.Zo())&&(b=new p9(a,b),g.N(this,b));b=new o9(a);g.N(this,b);g.lV(a,b.element,4)}},uDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.AP(c,b))},r9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)d9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.fg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Zb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Vj,index:Math.max(a.g.qB(),0),currentTime:0==f?void 0:f};(d=cBa(d))&&(c.locationInfo=d);d=c}else d=null;W8("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(Y8(d||null),s8()?p8().setLaunchParams(d||null):
n8("setLaunchParams called before ready.")):!d&&g9()&&V8()==b.key?g.YF("yt-remote-connection-change",!0):(d9(),Y8(d||null),d=U8().qe(),(d=V6(d,b.key))&&e9(d,1))}},KBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},r7={"'":"\\'"},wDa={},iBa={jY:"atp",L2:"ska",Z1:"que",k1:"mus",H2:"sus",s_:"dsp"};
O6.prototype.Sn=function(){var a=new O6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var a7,X6="",e7=b7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",CBa=b7("loadCastFramework")||b7("loadCastApplicationFramework"),MCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(h7,g.M);g.h=h7.prototype;g.h.OJ=function(a){this.A=arguments;this.g=!1;this.Ca?this.o=(0,g.F)()+this.rd:this.Ca=g.sg(this.B,this.rd)};
g.h.stop=function(){this.Ca&&(g.tg(this.Ca),this.Ca=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();h7.ba.V.call(this)};
g.h.PJ=function(){this.o?(this.Ca=g.sg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ca=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};i7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
i7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=j7.prototype;g.h.oi=null;g.h.Gf=!1;g.h.Sk=null;g.h.kw=null;g.h.Ck=null;g.h.Mj=null;g.h.nh=null;g.h.Kh=null;g.h.Ti=null;g.h.Rc=null;g.h.Um=0;g.h.Hf=null;g.h.Eq=null;g.h.oh=null;g.h.Il=-1;g.h.iE=!0;g.h.Yh=!1;g.h.Hs=0;g.h.Qp=null;var IBa={},m7={};g.h=j7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.nV=function(a){a=a.target;var b=this.Qp;b&&3==g.ix(a)?b.Kj():this.zF(a)};
g.h.zF=function(a){try{if(a==this.Rc)a:{var b=g.ix(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.xd&&!g.rc(10)||g.zd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cf&&!g.mx(this.Rc))break a;this.Yh||4!=b||7==c||(8==c||0>=d?this.g.Af(3):this.g.Af(2));t7(this);var e=this.Rc.getStatus();this.Il=e;var f=g.mx(this.Rc);(this.Gf=200==e)?(4==b&&p7(this),this.B?(JBa(this,b,f),g.cf&&this.Gf&&3==b&&(this.W.U(this.l,"tick",this.jV),this.l.start())):o7(this,f),this.Gf&&!this.Yh&&(4==b?this.g.Cp(this):
(this.Gf=!1,l7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.oh=3,n7(13)):(this.oh=0,n7(14)),p7(this),q7(this))}}catch(k){this.Rc&&g.mx(this.Rc)}finally{}};
g.h.jV=function(){var a=g.ix(this.Rc),b=g.mx(this.Rc);this.Um<b.length&&(t7(this),JBa(this,a,b),this.Gf&&4!=a&&l7(this))};
g.h.wU=function(a){s7((0,g.z)(this.vU,this,a),0)};
g.h.vU=function(a){this.Yh||(t7(this),o7(this,a),l7(this))};
g.h.sD=function(a){s7((0,g.z)(this.uU,this,a),0)};
g.h.uU=function(a){this.Yh||(p7(this),this.Gf=a,this.g.Cp(this),this.g.Af(4))};
g.h.cancel=function(){this.Yh=!0;p7(this)};
g.h.MU=function(){this.Sk=null;var a=(0,g.F)();0<=a-this.kw?(2!=this.Mj&&this.g.Af(3),p7(this),this.oh=2,n7(18),q7(this)):MBa(this,this.kw-a)};g.h=PBa.prototype;g.h.Fs=null;g.h.ye=null;g.h.Rp=!1;g.h.Ez=null;g.h.ho=null;g.h.Mt=null;g.h.Gs=null;g.h.Oe=null;g.h.Eg=-1;g.h.Hl=null;g.h.dl=null;g.h.connect=function(a){this.Gs=a;a=v7(this.g,null,this.Gs);n7(3);this.Ez=(0,g.F)();var b=this.g.F;null!=b?(this.Hl=b[0],(this.dl=b[1])?(this.Oe=1,QBa(this)):(this.Oe=2,x7(this))):(N6(a,"MODE","init"),this.ye=new j7(this,void 0,void 0,void 0),this.ye.oi=this.Fs,k7(this.ye,a,!1,null,!0),this.Oe=0)};
g.h.cJ=function(a){if(a)this.Oe=2,x7(this);else{n7(4);var b=this.g;b.Wf=b.bh.Eg;E7(b,9)}a&&this.Af(2)};
g.h.Sr=function(a){return this.g.Sr(a)};
g.h.abort=function(){this.ye&&(this.ye.cancel(),this.ye=null);this.Eg=-1};
g.h.Dz=function(){return!1};
g.h.lD=function(a,b){this.Eg=a.Il;if(0==this.Oe)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Wf=this.Eg;E7(c,2);return}this.Hl=c[0];this.dl=c[1]}else c=this.g,c.Wf=this.Eg,E7(c,2);else if(2==this.Oe)if(this.Rp)n7(7),this.Mt=(0,g.F)();else if("11111"==b){if(n7(6),this.Rp=!0,this.ho=(0,g.F)(),c=this.ho-this.Ez,!g.xd||g.rc(10)||500>c)this.Eg=200,this.ye.cancel(),n7(12),w7(this.g,this,!0)}else n7(8),this.ho=this.Mt=(0,g.F)(),this.Rp=!1};
g.h.Cp=function(){this.Eg=this.ye.Il;if(this.ye.Gf)0==this.Oe?this.dl?(this.Oe=1,QBa(this)):(this.Oe=2,x7(this)):2==this.Oe&&((!g.xd||g.rc(10)?!this.Rp:200>this.Mt-this.ho)?(n7(11),w7(this.g,this,!1)):(n7(12),w7(this.g,this,!0)));else{0==this.Oe?n7(9):2==this.Oe&&n7(10);var a=this.g;a.Wf=this.Eg;E7(a,2)}};
g.h.Km=function(){return this.g.Km()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Af=function(a){this.g.Af(a)};g.h=y7.prototype;g.h.tl=null;g.h.be=null;g.h.uc=null;g.h.Es=null;g.h.mo=null;g.h.Px=null;g.h.zo=null;g.h.sm=0;g.h.gQ=0;g.h.qd=null;g.h.fh=null;g.h.tg=null;g.h.di=null;g.h.bh=null;g.h.Dq=null;g.h.ak=-1;g.h.EA=-1;g.h.Wf=-1;g.h.Bj=0;g.h.oj=0;g.h.bi=8;var F7=new g.Cf;g.A(SBa,g.af);g.A(TBa,g.af);g.A(UBa,g.af);g.h=y7.prototype;g.h.connect=function(a,b,c,d,e){n7(0);this.Es=b;this.tl=c||{};d&&g.t(e)&&(this.tl.OSID=d,this.tl.OAID=e);this.C?(s7((0,g.z)(this.my,this,a),100),YBa(this)):this.my(a)};
g.h.my=function(a){this.bh=new PBa(this);this.bh.Fs=null;this.bh.l=this.B;this.bh.connect(a)};
g.h.Dz=function(){return 0==this.g};
g.h.qD=function(a){this.fh=null;aCa(this,a)};
g.h.pD=function(){this.tg=null;this.uc=new j7(this,this.o,"rpc",this.D);this.uc.oi=null;this.uc.Hs=0;var a=this.Px.clone();g.Dm(a,"RID","rpc");g.Dm(a,"SID",this.o);g.Dm(a,"CI",this.Dq?"0":"1");g.Dm(a,"AID",this.ak);z7(this,a);if(!g.xd||g.rc(10))g.Dm(a,"TYPE","xmlhttp"),k7(this.uc,a,!0,this.zo,!1);else{g.Dm(a,"TYPE","html");var b=this.uc,c=!!this.zo;b.Mj=3;b.nh=M6(a.clone());LBa(b,c)}};
g.h.lD=function(a,b){if(0!=this.g&&(this.uc==a||this.be==a))if(this.Wf=a.Il,this.be==a&&3==this.g)if(7<this.bi){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.tg){if(this.uc)if(this.uc.Ck+3E3<this.be.Ck)B7(this),this.uc.cancel(),this.uc=null;else break a;D7(this);n7(19)}}else this.EA=c[1],0<this.EA-this.ak&&37500>c[2]&&this.Dq&&0==this.oj&&!this.di&&(this.di=s7((0,g.z)(this.JQ,this),6E3));else E7(this,11)}else b!=wDa.mZ.g&&E7(this,11);else if(this.uc==a&&
B7(this),!g.C(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.ak=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.zo=e[2],e=e[3],null!=e?this.bi=e:this.bi=6,this.g=3,this.qd&&this.qd.by(),this.Px=v7(this,this.Km()?this.zo:null,this.Es),bCa(this)):"stop"==e[0]&&E7(this,7):3==this.g&&("stop"==e[0]?E7(this,7):"noop"!=e[0]&&this.qd&&this.qd.ay(e),this.oj=0)}}};
g.h.JQ=function(){null!=this.di&&(this.di=null,this.uc.cancel(),this.uc=null,D7(this),n7(20))};
g.h.Cp=function(a){if(this.uc==a){B7(this);this.uc=null;var b=2}else if(this.be==a)this.be=null,b=1;else return;this.Wf=a.Il;if(0!=this.g)if(a.Gf)1==b?(b=(0,g.F)()-a.Ck,F7.dispatchEvent(new TBa(F7,a.Ti?a.Ti.length:0,b,this.Bj)),A7(this),this.A.length=0):bCa(this);else{var c=a.oh,d;if(!(d=3==c||7==c||0==c&&0<this.Wf)){if(d=1==b)this.be||this.fh||1==this.g||2<=this.Bj?d=!1:(this.fh=s7((0,g.z)(this.qD,this,a),cCa(this,this.Bj)),this.Bj++,d=!0);d=!(d||2==b&&D7(this))}if(d)switch(c){case 1:E7(this,5);
break;case 4:E7(this,10);break;case 3:E7(this,6);break;case 7:E7(this,12);break;default:E7(this,2)}}};
g.h.xJ=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.fW=function(a){a?n7(2):(n7(1),dCa(this,8))};
g.h.Sr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.cx;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.Af=function(a){F7.dispatchEvent(new UBa(F7,a))};
g.h.Km=function(){return!(!g.xd||g.rc(10))};
g.h=eCa.prototype;g.h.by=function(){};
g.h.ay=function(){};
g.h.Zx=function(){};
g.h.Gr=function(){};
g.h.iz=function(){return{}};
g.h.isActive=function(){return!0};g.A(G7,g.M);g.h=G7.prototype;g.h.nU=function(){this.rd=Math.min(3E5,2*this.rd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.rd+15E3*Math.random();g.Zt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.rd=5E3};g.A(H7,eCa);g.h=H7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ud=function(a){return this.o.Ud(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ze(this.o),hCa(this),g.Ze(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new y7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.ak):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):I7(this)&&ZBa(this.g,c)};
g.h.by=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)ZBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Zx=function(a){var b=2==a&&401==this.g.Wf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Gr=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.iz=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.ay=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),XBa(this.g)):this.R("handlerMessage",new fCa(a[0],a[1]))};
g.h.PW=function(){this.l.isActive();var a=this.g,b=0;a.uc&&b++;a.be&&b++;0!=b||this.connect(this.B,this.A)};J7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
J7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
J7.prototype.B=function(a){a(Error("request timed out"))};var pCa=(0,g.F)(),M7=null,P7=Array(50),O7=-1,Q7=!1;g.A(R7,g.IF);R7.prototype.qe=function(){return this.g};
R7.prototype.contains=function(a){return!!U6(this.g,a)};
R7.prototype.get=function(a){return a?V6(this.g,a):null};
R7.prototype.info=function(a){N7(this.D,a)};g.A(S7,g.IF);var xDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=S7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ca)&&this.EF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ca)||(g.ZD(this.Ca),this.Ca=window.NaN)};
g.h.V=function(){this.stop();S7.ba.V.call(this)};
g.h.EF=function(){this.Ca=window.NaN;this.g=g.nE(K7(this.C,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.RW,this),onError:(0,g.z)(this.QW,this),xd:(0,g.z)(this.SW,this)})};
g.h.RW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new P6(c))};
g.h.QW=function(a){this.g=null;a.status&&404==a.status?this.l>=xDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=xDa[this.l],this.Ca=g.XD((0,g.z)(this.EF,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.SW=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(U7,R7);g.h=U7.prototype;g.h.start=function(){T7(this)&&this.R("screenChange");!g.QG("yt-remote-lounge-token-expiration")&&tCa(this);g.ZD(this.l);this.l=g.XD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){T7(this);qCa(this,a);V7(this,!1);this.R("screenChange");b(a);a.token||tCa(this)};
g.h.remove=function(a,b){var c=T7(this);sCa(this,a)&&(V7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.yq=function(a,b,c,d){var e=T7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,V7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.ZD(this.l);U7.ba.V.call(this)};
g.h.cK=function(a){T7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}V7(this,!b);b&&N7(this.D,"Missed "+b+" lounge tokens.")};
g.h.bK=function(a){N7(this.D,"Requesting lounge tokens failed: "+a)};g.A(X7,g.IF);g.h=X7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.QG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?Z7(this):(this.A=(0,g.F)()+3E5,g.PG("yt-remote-fast-check-period",this.A),this.Av())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){W7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!V6(a,d)},this);
Y7(this,b)};
g.h.V=function(){g.ZD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);X7.ba.V.call(this)};
g.h.Av=function(){g.ZD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=wCa(this);if(g.Ob(a)){var b=K7(this.B,"/pairing/get_screen_availability");this.l=L7(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.ST,this,a),(0,g.z)(this.RT,this))}else Y7(this,{}),Z7(this)};
g.h.ST=function(a,b){this.l=null;var c=g.Rb(wCa(this));if(g.ib(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Y7(this,d);Z7(this)}else this.gc("Changing Screen set during request."),this.Av()};
g.h.RT=function(a){this.gc("Screen availability failed: "+a);this.l=null;Z7(this)};
g.h.gc=function(a){N7("OnlineScreenService",a)};g.A($7,R7);g.h=$7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.yq=function(a,b,c,d){this.o.contains(a)?this.o.yq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,N7(this.D,a),d(Error(a)))};
g.h.qe=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.FF=function(){return(0,g.Kd)(this.qe(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.GF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new S7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ze(f);d(a8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.UW=function(a,b,c,d){g.nE(K7(this.C,"/pairing/get_screen"),{method:"POST",Ob:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new P6(d.screen||{});if(!e.name||ACa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);ACa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(a8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
xd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ze(this.o);g.Ze(this.l);$7.ba.V.call(this)};
g.h.rK=function(){BCa(this);this.R("screenChange");this.l.update()};
$7.prototype.dispose=$7.prototype.dispose;g.A(c8,g.IF);g.h=c8.prototype;g.h.Dp=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.we=function(a){this.ka()||(a&&d8(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){N7(this.K,a)};
g.h.IF=function(){return null};
g.h.Gv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){d8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Gv("");c8.ba.V.call(this)};g.A(e8,c8);g.h=e8.prototype;g.h.Fv=function(a){if(this.g){if(this.g==a)return;d8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);DCa(this)};
g.h.ck=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.we()},this),(0,g.z)(function(){this.we(Error("Failed to stop receiver app."))},this)):this.we(Error("Stopping cast device witout session."))};
g.h.Gv=g.y;g.h.V=function(){this.info("disposeInternal");g.ZD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;e8.ba.V.call(this)};
g.h.YU=function(a,b){if(!this.ka())if(b){var c=g.Xw(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":CCa(this,c.screenId);break;default:d8(this,"Unknown youtube message: "+d)}}else d8(this,"Unable to parse message.")}else d8(this,"No data in message.")};
g.h.uz=function(a,b,c,d){zCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(d8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.XD((0,g.z)(this.uz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.IF=function(){return this.g};
g.h.VW=function(a){this.ka()||a||(d8(this,"Cast session died."),this.we())};g.A(f8,c8);g.h=f8.prototype;g.h.Fv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.ck=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.ZD(this.C);this.A?this.A.stop((0,g.z)(this.we,this,null),(0,g.z)(this.we,this,"Failed to stop DIAL device.")):this.we()};
g.h.V=function(){this.g();this.g=g.y;g.ZD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;f8.ba.V.call(this)};
g.h.YW=function(a){this.ka()||a||(d8(this,"DIAL session died."),this.g(),this.g=g.y,this.we())};
g.h.At=function(a){this.I=T6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)}else this.D=(0,g.z)(function(){g.ZD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)},this),this.C=g.XD((0,g.z)(function(){this.D()},this),100)};
g.h.GL=function(a,b,c){zCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Dp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.At(b,c)},this),(0,g.z)(function(a){d8(this,"Failed to get DIAL screen: "+a);
this.At(b,c)},this))};g.A(g8,c8);g8.prototype.stop=function(){this.we()};
g8.prototype.Fv=g.y;g8.prototype.ck=function(){g.ZD(this.g);this.g=window.NaN;var a=V6(this.H.qe(),this.l.label);a?this.Dp(a):this.we(Error("No such screen"))};
g8.prototype.V=function(){g.ZD(this.g);this.g=window.NaN;g8.ba.V.call(this)};g.A(h8,g.IF);g.h=h8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.mD,this),(0,g.z)(this.AT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.uR,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),mCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.HF,this)),this.o=HCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.R("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.PV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.g.l.friendlyName),k8(this,null)}if(a&&b){if(!this.g){c=V6(this.l.qe(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}var d=GCa(this,c);d||(i8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.yg(a))},this)));
i8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);k8(this,new g8(this.l,d),!0)}this.g.Gv(b)}else i8("setConnectedScreenStatus: no screen.")};
g.h.QV=function(a){this.ka()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.ck(a):this.gc("Setting connection data without a session")};
g.h.XW=function(){this.ka()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.mD,this),(0,g.z)(this.ZT,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.HF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],jCa);g.Ze(this.g);h8.ba.V.call(this)};
g.h.gc=function(a){N7("Controller",a)};
g.h.nD=function(a,b){this.g==a&&(b||k8(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.wT=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:k8(this,new f8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:k8(this,new e8(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.uR=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return i8("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new f8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.GL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.At,b))};
g.h.mD=function(a){if(!this.ka()){i8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),k8(this,new e8(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=V6(this.l.qe(),c.label);
d&&Q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new e8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.nD,this,this.g)),this.g.ck(null));this.g.Fv(a)}}};
g.h.WW=function(){return this.g?this.g.IF():null};
g.h.ZT=function(a){this.ka()||(this.gc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&k8(this,null))};
g.h.AT=function(a){i8("Receiver availability updated: "+a);if(!this.ka()){var b=j8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.R("yt-remote-cast2-availability-change",j8(this))}};
g.h.HF=function(){this.ka()||(this.o=HCa(this),i8("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.QV;h8.prototype.setConnectedScreenStatus=h8.prototype.PV;h8.prototype.stopSession=h8.prototype.XW;h8.prototype.getCastSession=h8.prototype.WW;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.h=v8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+x8(this):this.H};
g.h.clone=function(){return new v8(B8(this))};g.A(D8,g.IF);g.h=D8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,J8(this,"play")):I8(this,"play"),H8(this,1,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,J8(this,"pause")):I8(this,"pause"),H8(this,2,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.pause)};
g.h.DF=function(a){if(1==this.g){if(this.l){var b=E8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,J8(this,"seekTo",{newTime:a}))}else I8(this,"seekTo",{newTime:a});H8(this,3,a);this.R("remotePlayerChange")}else F8(this,g.Ga(this.DF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,J8(this,"stopVideo")):I8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);G8(this,a);this.R("remotePlayerChange")}else F8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=E8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){N7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){N7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);I8(this,"setVolume",e)}c.muted=b;c.volume=a;G8(this,c)}else F8(this,g.Ga(this.setVolume,a,b))};
g.h.DE=function(a,b){if(1==this.g){var c=E8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.ec(d,c.l));I8(this,"setSubtitlesTrack",d);G8(this,c)}else F8(this,g.Ga(this.DE,a,b))};
g.h.rw=function(a,b){if(1==this.g){I8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Gb.id});var c=E8(this);c.audioTrackId=b.Gb.id;G8(this,c)}else F8(this,g.Ga(this.rw,a,b))};
g.h.CF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"previous")}else F8(this,g.Ga(this.CF,a,b))};
g.h.BF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"next")}else F8(this,g.Ga(this.BF,a,b))};
g.h.Jy=function(){1==this.g?I8(this,"dismissAutoplay"):F8(this,this.Jy)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}D8.ba.dispose.call(this)};
g.h.V=function(){UCa(this);this.A=null;this.B.clear();C8(this,null);D8.ba.V.call(this)};
g.h.tw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.qC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.rT=function(a,b){this.R(a,b)};
g.h.QQ=function(a){if(!a)this.xm(null),C8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)N7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,G8(this,b)}};
g.h.xm=function(a){N7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),VCa(this),this.R("remotePlayerChange")};
g.h.PQ=function(a){a?(VCa(this),this.R("remotePlayerChange")):this.xm(null)};
g.h.dR=function(){var a=RCa();a&&C8(this,a)};
g.h.gc=function(a){N7("CP",a)};g.A(K8,g.IF);g.h=K8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;y8(this.Za,m);this.A="UNSUPPORTED";L8("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",
params:g.yg(l)},a,qBa())}else L8("Connecting without params"),this.g.connect({},a,qBa());XCa(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),M8(this,3));K8.ba.dispose.call(this)};
g.h.V=function(){N8(this);P8(this);O8(this);g.ZD(this.H);this.H=window.NaN;g.ZD(this.I);this.I=window.NaN;this.o=null;g.sF(this.T);this.T.length=0;this.g.dispose();K8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.TJ=function(){this.C(2)};
g.h.VQ=function(){L8("Channel opened");this.M&&(this.M=!1,O8(this),this.K=g.XD((0,g.z)(function(){L8("Timing out waiting for a screen.");this.C(1)},this),15E3));
uBa(gCa(this.g),this.Z)};
g.h.RQ=function(){L8("Channel closed");(0,window.isNaN)(this.B)?$6(!0):$6();this.dispose()};
g.h.TQ=function(a){$6();(0,window.isNaN)(this.F())?(L8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,L8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),M8(this,2))};
g.h.UQ=function(a){a.params?L8("Received: action="+a.action+", params="+g.yg(a.params)):L8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.G)(a,function(a){return new O6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,!1);break;case "remoteConnected":var b=new O6(g.Xw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new O6(g.Xw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bDa(this,a);break;case "nowPlaying":dDa(this,a);break;case "onStateChange":cDa(this,a);break;case "onAdStateChange":eDa(this,a);break;case "onVolumeChanged":fDa(this,a);break;case "onSubtitlesTrackChanged":aDa(this,a);break;case "nowAutoplaying":gDa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":hDa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:L8("Unrecognized action: "+a.action)}};
g.h.yV=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&Q8(this,"getNowPlaying")}};
K8.prototype.subscribe=K8.prototype.subscribe;K8.prototype.unsubscribeByKey=K8.prototype.Ud;K8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?I7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
K8.prototype.getProxyState=K8.prototype.ga;K8.prototype.C=function(a){L8("Disconnecting with "+a);N8(this);this.R("beforeDisconnect",a);1==a&&$6();hCa(this.g,a);this.dispose()};
K8.prototype.disconnect=K8.prototype.C;K8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),A8(a,this.o,a.index));return B8(a)};
K8.prototype.getPlayerContextData=K8.prototype.fa;
K8.prototype.na=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.ZD(this.H),this.H=g.XD((0,g.z)(this.yV,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&z8(this.Za)==z8(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
K8.prototype.setPlayerContextData=K8.prototype.na;K8.prototype.X=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
K8.prototype.getOtherConnectedRemoteId=K8.prototype.X;K8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
K8.prototype.getReconnectTimeout=K8.prototype.F;K8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
K8.prototype.getAutoplayMode=K8.prototype.Y;K8.prototype.ca=function(){return this.D||""};
K8.prototype.getAutoplayVideoId=K8.prototype.ca;K8.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.$t(a.g);a.start()}};
K8.prototype.reconnect=K8.prototype.sa;K8.prototype.ha=function(a,b){Q8(this,a,b);ZCa(this)};
K8.prototype.sendMessage=K8.prototype.ha;g.A(R8,R7);g.h=R8.prototype;g.h.qe=function(a){return this.fd.$_gs(a)};
g.h.contains=function(a){return!!this.fd.$_c(a)};
g.h.get=function(a){return this.fd.$_g(a)};
g.h.start=function(){this.fd.$_st()};
g.h.add=function(a,b,c){this.fd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.fd.$_r(a,b,c)};
g.h.yq=function(a,b,c,d){this.fd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.fd.$_ubk(this.l[a]);this.l.length=0;this.fd=null;R8.ba.V.call(this)};
g.h.TW=function(){this.R("screenChange")};
g.h.SS=function(){this.R("onlineScreenChange")};
$7.prototype.$_st=$7.prototype.start;$7.prototype.$_gspc=$7.prototype.UW;$7.prototype.$_gsppc=$7.prototype.GF;$7.prototype.$_c=$7.prototype.contains;$7.prototype.$_g=$7.prototype.get;$7.prototype.$_a=$7.prototype.add;$7.prototype.$_un=$7.prototype.yq;$7.prototype.$_r=$7.prototype.remove;$7.prototype.$_gs=$7.prototype.qe;$7.prototype.$_gos=$7.prototype.FF;$7.prototype.$_s=$7.prototype.subscribe;$7.prototype.$_ubk=$7.prototype.Ud;var S8=null,T8=null,h9=null,X8=[];g.q(i9,g.M);g.h=i9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.kD,this);this.g.unsubscribe("remotePlayerChange",this.Am,this);this.g.unsubscribe("remoteQueueChange",this.Ep,this);this.g.unsubscribe("autoplayUpNext",this.IC,this);this.g.unsubscribe("previousNextChange",this.hD,this);this.g.unsubscribe("nowAutoplaying",this.ZC,this);this.g.unsubscribe("autoplayDismissed",this.HC,this);this.g=this.F=null};
g.h.KB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!E8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":E8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Kj(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.rw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.rw(this.l.getVideoData(1).videoId,c)}};
g.h.OQ=function(a){this.J.OJ(a)};
g.h.uW=function(a){this.KB("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.TE=function(){var a=this.l.yc("captions","track");g.Xb(a)||m9(this,a)};
g.h.XC=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.Am,this);var b=Math.round(a.volume);a=!!a.muted;var c=E8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.Am,this)}};
g.h.kS=function(){g.Xb(this.C)||tDa(this,this.C);this.D=!1};
g.h.kD=function(a,b){this.B.stop();2==b&&this.QE()};
g.h.Am=function(){if(l9(this)){this.A.stop();var a=E8(this.g);switch(a.g){case 1081:case 1:k9(this,new g.qP(8));this.PE();break;case 1085:case 3:k9(this,new g.qP(9));break;case 1083:case 0:k9(this,new g.qP(2));this.I.stop();j9(this,this.l.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.qP(4));break;case 2:k9(this,new g.qP(4));j9(this,z8(a));break;case -1:k9(this,new g.qP(64));break;case -1E3:k9(this,new g.qP(128,{errorCode:"mdx.remoteerror",message:"\u0647\u0630\u0627 \u0627\u0644\u0641\u064a\u062f\u064a\u0648 \u063a\u064a\u0631 \u0645\u062a\u0627\u062d \u0644\u0644\u062a\u0634\u063a\u064a\u0644 \u0639\u0646 \u0628\u064f\u0639\u062f."}))}a=
E8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,tDa(this,a));a=E8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.pF()}else sDa(this)};
g.h.hD=function(){this.l.R("mdxpreviousnextchange")};
g.h.Ep=function(){l9(this)||sDa(this)};
g.h.bJ=function(){this.g.Jy()};
g.h.IC=function(a){a&&(a=g.nE("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.zU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.zU=function(a,b){var c=new g.kO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.ZC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.HC=function(){this.l.R("mdxautoplaycanceled")};
g.h.NO=function(a,b){-1==E8(this.g).g?n9(this,a):b&&this.g.DF(a)};
g.h.pF=function(){if(l9(this)){var a=E8(this.g);this.o.Ea(this.T);a.muted?this.l.mute():this.l.gg();this.l.setVolume(a.volume);this.T=this.o.O(this.l,"onVolumeChange",this.XC)}};
g.h.PE=function(){this.A.stop();if(!this.g.ka()){var a=E8(this.g);a.kb()&&k9(this,new g.qP(8));j9(this,z8(a));this.A.start()}};
g.h.QE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.q(o9,g.W);o9.prototype.B=function(a){vDa(this,a.state)};g.q(p9,g.VZ);p9.prototype.J=function(){var a=this.l.yc("remote","receivers");a&&1<a.length&&!this.l.yc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.WZ(this,(0,g.G)(a,this.C)),a=this.l.yc("remote","currentReceiver"),this.zf(this.C(a)),this.enable(!0)):this.enable(!1)};
p9.prototype.C=function(a){return a.key};
p9.prototype.yf=function(a){return"cast-selector-receiver"==a?"\u0625\u0631\u0633\u0627\u0644...":this.H[a].name};
p9.prototype.ud=function(a){g.VZ.prototype.ud.call(this,a);this.l.Pd("remote","currentReceiver",this.H[a]);this.B.Rb()};g.q(q9,g.rV);g.h=q9.prototype;g.h.create=function(){mDa(g.HM(g.Y(this.g)));this.C.push(g.UF("yt-remote-before-disconnect",this.KQ,this));this.C.push(g.UF("yt-remote-connection-change",this.BT,this));this.C.push(g.UF("yt-remote-receiver-availability-change",this.iD,this));this.C.push(g.UF("yt-remote-auto-connect",this.zT,this));this.C.push(g.UF("yt-remote-receiver-resumed",this.yT,this));this.iD()};
g.h.load=function(){this.g.tu();g.rV.prototype.load.call(this);this.B=new i9(this,this.g,this.l);var a=(a=rDa())?a.currentTime:0;var b=g9()?new D8(b9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));uDa(this,this.D,this.D);g.s0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.rV.prototype.unload.call(this);g.s0(this.g.app,5)};
g.h.V=function(){g.VF(this.C);g.rV.prototype.V.call(this)};
g.h.lm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.KB.apply(this.B,[a].concat(g.pa(c)))};
g.h.KJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Zf=function(){return this.l?E8(this.l).Zf:!1};
g.h.hasNext=function(){return this.l?E8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.BO=function(){var a=E8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+x8(a):a.A,isPeggedToLive:1>=(a.C?a.o+x8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+x8(a):a.o,seekableStart:0<a.B?a.B+x8(a):a.B}};
g.h.CO=function(){this.l&&this.l.BF()};
g.h.DO=function(){this.l&&this.l.CF()};
g.h.KQ=function(a){1==a&&(this.I=this.l?E8(this.l):null)};
g.h.BT=function(){var a=g9()?new D8(b9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.oB(a.videoId,z8(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.iD=function(){this.F=[this.o].concat(oDa());var a=c9()||this.o;r9(this,a);this.g.va("onMdxReceiversChange")};
g.h.zT=function(){var a=c9();r9(this,a)};
g.h.yT=function(){this.A=c9()};
g.h.AO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?t8():r9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&t8(),!0):!1}};
g.h.EO=function(){I8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ic=function(){return!1};g.hY.remote=q9;})(_yt_player);
